-- =============================================================================
-- Migration 001: Initial Schema
-- Canadian Retirement Planner — Supabase / Postgres
--
-- Region: Canada Central (ca-central-1) — required for PIPEDA compliance.
-- Run via: supabase db reset  OR  apply via Supabase Dashboard SQL editor.
--
-- All tables use CREATE TABLE IF NOT EXISTS for idempotency.
-- Indexes are created with CREATE INDEX IF NOT EXISTS for the same reason.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- Table: public.users
--
-- Mirrors Supabase Auth users (auth.users) with app-specific profile data.
-- This row is created automatically by the handle_new_user() trigger defined
-- in migration 002, which fires on every auth.users INSERT (Google OAuth and
-- magic link both go through that path).
--
-- Columns:
--   id                  — matches auth.users.id exactly (UUID, PK)
--   email               — user's email address (copied from auth.users)
--   display_name        — human-readable name; populated from Google OAuth
--                         raw_user_meta_data->>'full_name', null for magic-link
--                         signups until the user sets it
--   avatar_url          — profile photo URL from Google OAuth; null otherwise
--   subscription_override — null = normal user (access determined by Stripe);
--                           'beta' = override grants full paid access, bypasses
--                           Stripe entirely; 'lifetime' = same as beta but
--                           permanent. Set manually via Supabase Studio or by
--                           the admin-invites Edge Function. NOT overwritten on
--                           subsequent sign-ins (see trigger in migration 002).
--   stripe_customer_id  — Stripe cus_xxx ID. Null until the user initiates a
--                         Stripe checkout; set by the create-checkout-session
--                         Edge Function. Indexed for fast webhook lookups.
--   created_at          — row creation timestamp (UTC)
--   updated_at          — last upsert timestamp (UTC); updated by trigger on
--                         every sign-in
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id                    uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email                 text        NOT NULL,
  display_name          text,
  avatar_url            text,
  subscription_override text,                    -- null | 'beta' | 'lifetime'
  stripe_customer_id    text,                    -- set by create-checkout-session Edge Function
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- Index on stripe_customer_id: Stripe webhook handler looks up users by
-- customer ID on every billing event (payment success, failure, cancellation).
CREATE INDEX IF NOT EXISTS users_stripe_customer_id_idx
  ON public.users(stripe_customer_id);


-- ---------------------------------------------------------------------------
-- Table: public.scenarios
--
-- Each row is one retirement planning scenario belonging to a user.
-- Users may have multiple scenarios (e.g. "Early Retirement", "Conservative").
-- Free tier limit (e.g. 1 scenario) is enforced at the application layer by
-- checking count before insert — not enforced in the DB schema.
--
-- Columns:
--   id         — UUID primary key, generated by Postgres
--   user_id    — owner; CASCADE delete removes all scenarios when user is deleted
--   name       — display name shown in the scenario list (e.g. "My Retirement
--                Plan"). Denormalized here so the list UI does not need to
--                parse the full data blob.
--   data       — full scenario object as JSONB. Shape matches the scenario
--                object defined in src/constants/defaults.js (all wizard
--                inputs: personal, CPP/OAS, pensions, savings, assets,
--                liabilities, expenses, withdrawal order, estate fields).
--   created_at — row creation timestamp (UTC)
--   updated_at — last save timestamp (UTC); updated by the app on every save
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.scenarios (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name        text        NOT NULL DEFAULT 'My Retirement Plan',
  data        jsonb       NOT NULL,              -- full scenario object (matches defaults.js shape)
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Index on user_id: every scenario query is scoped to the authenticated user.
CREATE INDEX IF NOT EXISTS scenarios_user_id_idx
  ON public.scenarios(user_id);


-- ---------------------------------------------------------------------------
-- Table: public.subscriptions
--
-- Subscription state synced from Stripe via the stripe-webhook Edge Function.
-- This table is WRITE-ONLY from the server side — no client INSERT/UPDATE/DELETE
-- policies exist (see migration 002). Clients read their own row to determine
-- feature access level.
--
-- The Stripe subscription ID (sub_xxx) is used as the primary key so upserts
-- in the webhook handler are simple and idempotent.
--
-- Columns:
--   id                   — Stripe subscription ID (sub_xxx), text PK
--   user_id              — owning user; CASCADE delete cleans up on user removal
--   stripe_customer_id   — Stripe customer ID (cus_xxx); indexed for webhook
--                          lookups alongside users.stripe_customer_id
--   status               — Stripe subscription status string:
--                            'trialing'   → full paid access (within trial)
--                            'active'     → full paid access
--                            'past_due'   → payment failed; show warning but
--                                           maintain access briefly
--                            'canceled'   → paid features revoked
--                            'incomplete' → payment setup failed; no paid access
--   price_id             — Stripe price ID (price_xxx); distinguishes monthly
--                          vs. annual plans
--   current_period_start — start of current billing period (UTC)
--   current_period_end   — end of current billing period / renewal date (UTC)
--   trial_end            — when the trial expires; null if not on trial (UTC)
--   cancel_at_period_end — true when user has requested cancellation at period end
--   created_at           — row creation timestamp (UTC)
--   updated_at           — last webhook sync timestamp (UTC)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                   text        PRIMARY KEY,  -- Stripe subscription ID (sub_xxx)
  user_id              uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stripe_customer_id   text        NOT NULL,     -- cus_xxx
  status               text        NOT NULL,     -- 'trialing' | 'active' | 'past_due' | 'canceled' | 'incomplete'
  price_id             text        NOT NULL,     -- Stripe price ID (monthly or annual)
  current_period_start timestamptz,
  current_period_end   timestamptz,
  trial_end            timestamptz,
  cancel_at_period_end boolean     NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- Index on user_id: client queries filter by authenticated user.
CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx
  ON public.subscriptions(user_id);

-- Index on stripe_customer_id: webhook handler resolves user from Stripe
-- customer ID before upserting subscription state.
CREATE INDEX IF NOT EXISTS subscriptions_stripe_customer_id_idx
  ON public.subscriptions(stripe_customer_id);


-- ---------------------------------------------------------------------------
-- Table: public.ai_usage
--
-- Tracks per-user monthly AI generation counts.
-- Incremented atomically by the Gemini proxy Edge Function before proxying
-- each request. The Edge Function rejects with HTTP 429 when count >= 30.
--
-- Free users are blocked before reaching the Edge Function entirely — this
-- table only records usage for paid (or override) users.
--
-- Columns:
--   id         — UUID primary key
--   user_id    — owning user; CASCADE delete cleans up on user removal
--   period     — billing month as 'YYYY-MM' (e.g. '2026-03'), derived from
--                current UTC date at the time of the AI request
--   count      — number of AI generations made in this period (default 0)
--   created_at — row creation timestamp (UTC)
--   updated_at — last increment timestamp (UTC)
--
-- Uniqueness constraint on (user_id, period) ensures one row per user per
-- month; the Edge Function uses INSERT ... ON CONFLICT DO UPDATE to increment.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_usage (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  period      text        NOT NULL,              -- 'YYYY-MM' (billing month)
  count       integer     NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  UNIQUE (user_id, period)
);

-- Composite index on (user_id, period): the Edge Function always queries
-- by both columns to check or increment the current month's count.
CREATE INDEX IF NOT EXISTS ai_usage_user_period_idx
  ON public.ai_usage(user_id, period);
